### ISSUE TITLE
Timeout on ProduceAsync depending on the topic

### ISSUE THREAD

**Issue by NicolasReyDotNet** [confluentinc/confluent-kafka-dotnet#1316]
Description
===========
Hi,
When I produce a message to a Kafka topic, if I doesn't use the "test-topic" topic (default ?) I finally get a Timeout.
If I do use the test-topic" topic name everything works fine.

Is there any missing configuration on my topics to accept published message ?

How to reproduce
================

This is perfectly working 
```
            var config = new ProducerConfig { BootstrapServers = "kafka:9092" };

            using (var p = new ProducerBuilder<Null, string>(config).Build())
            {
                try
                {

                    var strMessage = JsonConvert.SerializeObject(message);
                    var dr = await p.ProduceAsync("test-topic", new Message<Null, string> { Value = strMessage });  
                    Console.WriteLine($"Delivered '{dr.Value}' to '{dr.TopicPartitionOffset}'");
                }
                catch (ProduceException<Null, string> e)
                {
                    Console.WriteLine($"Delivery failed: {e.Error.Reason}");
                }
            }
```

This is throwing an exception after a long timeout (note I only changed the topic name to "test1" that does exists) 
```
            var config = new ProducerConfig { BootstrapServers = "kafka:9092" };

            using (var p = new ProducerBuilder<Null, string>(config).Build())
            {
                try
                {

                    var strMessage = JsonConvert.SerializeObject(message);
                    var dr = await p.ProduceAsync("test1", new Message<Null, string> { Value = strMessage });  
                    Console.WriteLine($"Delivered '{dr.Value}' to '{dr.TopicPartitionOffset}'");
                }
                catch (ProduceException<Null, string> e)
                {
                    Console.WriteLine($"Delivery failed: {e.Error.Reason}");
                }
            }
```
This is the exception 
![image](https://user-images.githubusercontent.com/37657851/84163224-88b7e180-aa71-11ea-98c6-ca4c3f850177.png)

My docker-compose configuration 
```
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "test1:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

Here are the list of topics inside my kafka container 
![image](https://user-images.githubusercontent.com/37657851/84163030-573f1600-aa71-11ea-8ddc-59e704c2d238.png)

Both "topic-test" and "test1" exist

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.

 - [x] Confluent.Kafka nuget version.
**v 1.4.3**

 - [x] Apache Kafka version.
**2.12-2.2.0 from https://microbadger.com/images/wurstmeister/kafka**

 - [x] Client configuration.
**.net core 3.1**

 - [x] Operating system.
**Windows 10 Pro with Docker Desktop 2.3.0.3**
