### ISSUE TITLE
Cooperative Sticky strategy behaves wrong after adding new consumer

### ISSUE THREAD

**Issue by lichutin-st** [confluentinc/confluent-kafka-dotnet#1712]
Description
===========
Hello! I started using cooperative sticky assignment strategy in my projects and realized strange behavior when new consumer is added to the consumer group.

We have two topics with 4 partitions each. When I start one consumer, all the partitions for both topics are assigned to that consumer.
When I start second consumer in the same group I expect to have two partitions of every topic assigned to each consumer. Instead, the first consumer gets 4 partitions of the first topic, and the second consumer gets 4 partitions of the second topic.

Moreover, if I start two consumers at the same time, both gets 2 partitions of each topic. But when a consumer fails and then started again, it gets 4 partitions of the same topic.

kafka-consumer-groups has such output
```
.\kafka-consumer-groups --bootstrap-server localhost:9092 --describe --group localconsumers --members --verbose

GROUP           CONSUMER-ID                                  HOST            CLIENT-ID       #PARTITIONS     ASSIGNMENT
localconsumers  rdkafka-c39093ca-70e7-458c-b6f1-ed5dd4f6e78e /192.168.0.1    rdkafka         4               first.topic(0,1,2,3)
localconsumers  rdkafka-0d0d301f-8ae7-4f99-9f19-23cbcaeb7a26 /192.168.0.1    rdkafka         4               second.topic(0,1,2,3)
```
 
I'm using Confluent.Kafka 1.8.2 and docker images for kafka & zookeeper (latest versions). 
Behavior is the same if I launch apps under Windows or Linux

How to reproduce
================

docker-compose.yml
```
version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  kafka:
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9093,PLAINTEXT_HOST://localhost:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_LOG4J_LOGGERS=kafka.controller=WARN,state.change.logger=WARN,kafka.log.LogCleaner=WARN,kafka=WARN,state.change.logger=WARN
    depends_on:
      - zookeeper
```

Program.cs
```
class Program
    {
        const string BoostrapUrl = "localhost:9092";
        const string GroupId = "localconsumers";
        const string FirstTopic = "first.topic";
        const string SecondTopic = "second.topic";

        static async Task Main(string[] args)
        {
            await CreateTopicsIfNotExistAsync();

            var config = new ConsumerConfig
            {
                BootstrapServers = BoostrapUrl,
                GroupId = GroupId,
                EnableAutoCommit = false,
                AutoOffsetReset = AutoOffsetReset.Earliest,
                PartitionAssignmentStrategy = PartitionAssignmentStrategy.CooperativeSticky
            };

            var cb = new ConsumerBuilder<string, string>(config);
            cb.SetPartitionsAssignedHandler((c, partitions) =>
            {
                partitions.ForEach(p => Console.WriteLine($"Assigned: {p}"));
            });
            cb.SetPartitionsRevokedHandler((c, partitions) =>
            {
                partitions.ForEach(p => Console.WriteLine($"Revoked: {p}"));
            });
            var consumer = cb.Build();
            consumer.Subscribe(new[] { FirstTopic, SecondTopic });

            while (true)
            {
                var consumed = consumer.Consume();
                Console.WriteLine($"Message: {consumed}");
            }
        }

        static async Task CreateTopicsIfNotExistAsync()
        {
            var config = new AdminClientConfig
            {
                BootstrapServers = BoostrapUrl,
            };

            using (var adminClent = new AdminClientBuilder(config).Build())
            {
                var firstTopic = new TopicSpecification
                {
                    Name = FirstTopic,
                    ReplicationFactor = 1,
                    NumPartitions = 4,
                };
                var secondTopic = new TopicSpecification
                {
                    Name = SecondTopic,
                    ReplicationFactor = 1,
                    NumPartitions = 4,
                };

                try
                {
                    await adminClent.CreateTopicsAsync(new List<TopicSpecification> { firstTopic, secondTopic });
                }
                catch (CreateTopicsException ex)
                {
                    if (ex.Results.Select(r => r.Error.Code).Where(el => el != ErrorCode.TopicAlreadyExists && el != ErrorCode.NoError).Count() > 0)
                    {
                        throw new Exception("Unable to create topics", ex);
                    }
                }
            }
        }
    }
```

You can start one consumer and then start another one. The output should look like this one
![image](https://user-images.githubusercontent.com/68215827/139409005-a651d8f0-c0ad-45e8-af91-21c99618542c.png)

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.
 - [x] Apache Kafka version.
 - [x] Client configuration.
 - [x] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.
