### ISSUE TITLE
Nuget Confluent.Kafka - ProducerBuilder.Build() not working with Kafka latest version but working fine with 1.7.0 for on-prem producer 

### ISSUE THREAD

**Issue by rahul-kumar2** [confluentinc/confluent-kafka-dotnet#1794]
Description
===========
We are writing Kafka producer for an On-prem environment where we are setting Keystore location (.pkcs12) and password.
 
Problem is  _producerBuilder.Build() line stopping the .net console application and not even throwing any exception.

We tested it first with Kafka version **1.8.2** and it was not working.

Next, we reduced it to **1.7.0,** and then it worked no exception and all.

Not sure what has been changed in the latest version of Kafka that breaks this feature.

Could you please check? 

Feel free to ask anything that is required to reproduce this in case, not re-producible. 

Working version :

    PackageReference Include="Confluent.Kafka" Version="1.7.0" 
    PackageReference Include="Confluent.SchemaRegistry.Serdes.Avro" Version="1.7.0" 

Not working version :

   PackageReference Include="Confluent.Kafka" Version="1.8.2"  
  PackageReference Include="Confluent.SchemaRegistry.Serdes.Avro" Version="1.8.2"  

How to reproduce
================

`
 public void Send()
    {
        ProducerConfig _producerConfiguration = new ProducerConfig();

        _producerConfiguration.BootstrapServers = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:9093";
        _producerConfiguration.SaslUsername = "xxxxxxxx";
        _producerConfiguration.SaslPassword = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";

        _producerConfiguration.SslKeystoreLocation = "keystore.pkcs12";
        _producerConfiguration.SslKeystorePassword = "xxxxxxxxxxxxxxxxxxxxxxxxxxxx";

        _producerConfiguration.SslKeyLocation = "key.pem";
        _producerConfiguration.SslKeyPassword = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";

        _producerConfiguration.MessageSendMaxRetries = 3;
        _producerConfiguration.MaxInFlight = 1;
        _producerConfiguration.EnableSslCertificateVerification = false;

        _producerConfiguration.SaslMechanism = SaslMechanism.ScramSha256;
        _producerConfiguration.SecurityProtocol = SecurityProtocol.SaslSsl;
        _producerConfiguration.Debug = "all";

        SchemaRegistryConfig schemaRegistry = new SchemaRegistryConfig();
        schemaRegistry.Url = "https://xxxxxxxxxxxxxxxxxxxxxxx:8081";
        schemaRegistry.SslKeystoreLocation = "keystore.pkcs12";
        schemaRegistry.SslKeystorePassword = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";

     
        try
        {
            CachedSchemaRegistryClient _cachedSchemaRegistryClient = new CachedSchemaRegistryClient(schemaRegistry);           

            ProducerBuilder<Anything, string> _producerBuilder = new ProducerBuilder<Anything, string>(_producerConfiguration);
            AvroSerializerConfig avroconfig = new AvroSerializerConfig
            {
                AutoRegisterSchemas = false
            };

            _producerBuilder.SetKeySerializer(new AvroSerializer<Anything>(_cachedSchemaRegistryClient, avroconfig).AsSyncOverAsync());
            _producerBuilder.SetValueSerializer(new AvroSerializer<string>(_cachedSchemaRegistryClient, avroconfig).AsSyncOverAsync());

            _producerBuilder.SetErrorHandler((_, error) =>Console.WriteLine(error));
           
            Console.WriteLine("Build started !");        

            var data = _producerBuilder.Build();

            Console.WriteLine("Build done !");
            Console.WriteLine("Press any key to exit !");
            Console.ReadLine();
        }
        catch (KafkaException ex)
        {
            Console.WriteLine("Press any key to exit !");
            Console.ReadLine();

        }
        catch (Exception ex)
        {
            Console.WriteLine("Press any key to exit !");
            Console.ReadLine();
            throw;
        }
    }`

Checklist
=========
Working version :
    PackageReference Include="Confluent.Kafka" Version="1.7.0" 
    PackageReference Include="Confluent.SchemaRegistry.Serdes.Avro" Version="1.7.0" 
Not working version :
   PackageReference Include="Confluent.Kafka" Version="1.8.2" 
  PackageReference Include="Confluent.SchemaRegistry.Serdes.Avro" Version="1.8.2"

**Comment by mhowlett** [comment]
that's weird, build should never block.
can you set the `debug` property to `all` and capture the output?

**Comment by rahul-kumar2** [comment]
@mhowlett  We already did that in the above code     _producerConfiguration.Debug = "all";
but this one is not printing anything as run-time utility stopping without any error.It seems like inline with this issue https://github.com/confluentinc/confluent-kafka-dotnet/issues/1708  and may be fixed in nxt version.

**Comment by mhowlett** [comment]
seems likely, so i'll close this issue now, but please open again if this is not resolved in 1.9.0.

we should have an RC build of 1.9.0 on nuget relatively soon.

**Comment by alexrosenfeld10** [comment]
@mhowlett I am getting the same issue, I think. My `ProducerBuilder` just hangs - no exception, but never moves forward, even after a VERY long time. More details, it's a bit odd though:

Firstly, here is my example / test code:

```csharp
...
        Console.WriteLine("about to set up producer");
        using var producer = new ProducerBuilder<string, TEvent>(producerConfig)
            .SetErrorHandler((_, e) =>
            {
                if (e.IsFatal)
                {
                    Console.WriteLine($"ERROR: Kafka fatal error: {e.Reason}");
                }
                else
                {
                    if (e.Code != ErrorCode.Local_AllBrokersDown)
                    {
                        Console.WriteLine($"WARNING: Kafka error: {e.Reason}");
                    }
                }
            })
            .SetLogHandler((_, m) => { Console.WriteLine(m.Message); })
            .SetStatisticsHandler((_, e) => { Console.WriteLine(e); })
            .SetValueSerializer(new AvroSerializer<TEvent>(schemaRegistry, new AvroSerializerConfig
            {
                AutoRegisterSchemas = false
            })).Build();

        Console.WriteLine("about to create message");
        var message = new Message<string, TEvent>
... 
```

1. Works fine locally, natively on my macOS M1
2. Works fine in a docker container that I build locally
3. Fails when running in the docker container I'm building in GHA. The command I'm building it with is:



```yaml
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: mycompany-docker.jfrog.io
          username: ${{ secrets.ORG_JFROG_USERNAME }}
          password: ${{ secrets.ORG_JFROG_ACCESS_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: mycompany-docker.jfrog.io/mycompany/myapp
          tags: |
            type=sha
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

I am at a loss on this one, it's very hard to know where to go from here. Hoping someone in this thread can help me
