### ISSUE TITLE
1.9.0-RC7: High CPU Utilization with Producer

### ISSUE THREAD

**Issue by ryanliang** [confluentinc/confluent-kafka-dotnet#1809]
Description
===========
When producing messages with `Produce` function, we are seeing high CPU utilization for librdkafka thread under Process Explorer(screenshots attached below).  This is only first seen with version v1.9.0.  Compared to v1.8.2, the CPU utilization for this thread is **increased from <0.01% to around 12%.**

How to reproduce
================
<details>
  <summary>docker-compose.yml</summary>
  
  ```yml
    ---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  ```
</details>

<details>
  <summary>program.cs</summary>
  
  ```cs
using System;
using Confluent.Kafka;

namespace KafkaNetDemo
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var producerConfig = new ProducerConfig
            {
                BootstrapServers = "localhost:9092",
            };

            using var producer = new ProducerBuilder<string, string>(producerConfig).Build();

            Console.WriteLine("Press c and enter to replicate the issue and q to exit");
            
            while (Console.ReadKey().KeyChar != 'q')
            {
                for (var i = 0; i < 5; i++)
                {
                    var value = $"test_{i}_{DateTime.Now}";

                    try
                    {
                        producer.Produce("test", new Message<string, string> { Key = "key", Value = value });
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine(e);
                    }
                }
            }
        }
    }
}
  ```
</details>
v1.9.0-RC7 (CPU Utilization around 12%)

![github_v190rc7_cpu](https://user-images.githubusercontent.com/823147/167174176-4494f88c-2fd1-44f0-8918-82b56a8283c6.png)

v1.8.2 (CPU Utilization <0.01%)
![github_v182_cpu](https://user-images.githubusercontent.com/823147/167174185-ac8c89e0-9907-423e-b506-89660524f617.png)

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version. 1.9.0-RC7
 - [x] Apache Kafka version. confluentinc/cp-kafka:7.0.0
 - [ ] Client configuration.
 - [x] Operating system. Windows 10 21H2, Windows Server 2016 Standard
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [x] Critical issue.
