### ISSUE TITLE
Client does not re-establish connection to brokers

### ISSUE THREAD

**Issue by okomen-foreflight** [confluentinc/confluent-kafka-dotnet#2215]
Description
===========
Hello,
I am running a 3-broker MSK cluster in production and whenever AWS makes a rolling update, i.e. taking one broker down, updating it and spinning it back up, my consumers eventually all stop once all brokers have been updated. 
I therefore tried to replicate this issue in a local 3-broker kafka cluster, setup in docker compose (see configuration below if relevant). 

My consumer looks like this:

```
var consumerConfig = new ConsumerConfig
        {
            BootstrapServers = kafkaSecrets.Value.InternalKafkaBootstrapServers,
            GroupId = groupId,
            SecurityProtocol = SecurityProtocol.Plaintext,
            AutoOffsetReset = autoOffsetReset,
            EnableAutoCommit = false,
            AutoCommitIntervalMs = 0,
        };
using var fleetTailPositionsConsumer = new ConsumerBuilder<string, ProtoFleetMessage>(consumerConfig)
            .SetValueDeserializer(new ProtobufDeserializer<ProtoFleetMessage>().AsSyncOverAsync())
            .SetPartitionsAssignedHandler((_, assignedPartitions) =>
            {
                Console.WriteLine("Does not matter what code is here. As oon as there is a partitons assigned handler. it stops working");
                Thread.Sleep(10000);
            })
            .SetErrorHandler((_, error) =>
            {
                if (error.IsFatal)
                    logger.LogCritical("Fatal fleet kafka aircraft consumer error: {@Error}", error);
                else
                    logger.LogWarning("Non-fatal fleet aircraft kafka consumer error {@Error}", error);
            })
            .Build();
        
        fleetTailPositionsConsumer.Subscribe(KafkaConstants.FLEET_TAIL_POSITIONS_TOPIC);
        
        while (!cancellationToken.IsCancellationRequested)
        {
            await CleanFlightIdCache();
            ConsumeResult<string, ProtoFleetMessage>? consumeResult = null;
            try
            {
                consumeResult = fleetTailPositionsConsumer.Consume(cancellationToken);

           ...
```
I have tried with and without EnableAutoCommit making no difference. After a while I get this log:
%4|1715001030.020|SESSTMOUT|rdkafka#consumer-5| [thrd:main]: Consumer group session timed out (in join-state steady) after 45265 ms without a successful response from the group coordinator (broker -1, last error was Broker: Not coordinator): revoking assignment and rejoining group
%4|1715001030.789|SESSTMOUT|rdkafka#consumer-12| [thrd:main]: Consumer group session timed out (in join-state steady) after 45130 ms without a successful response from the group coordinator (broker -1, last error was Success): revoking assignment and rejoining group

It only happens when I have a PartitionsAssignedHandler. Which is interesting, because setting a breakpoint inside the handler reveals that isn't even called.

**Docker compose configuration**
```
  kafka0:
    image: 'bitnami/kafka:latest'
    container_name: kafka0
    ports:
      - '9092:9092'
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka0:9093,1@kafka1:9093,2@kafka2:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka0:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_CFG_LOG_RETENTION_MS=60000 # Only retain messages for one minute
      - KAFKA_CFG_LOG_SEGMENT_BYTES=1073741824 # 1 GB
      - KAFKA_CFG_SEGMENT_MS=60000 # only retain segments for 1 hour
      - KAFKA_CFG_LOG_CLEANUP_POLICY=delete # delete log messages
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_KRAFT_CLUSTER_ID=asdsataoitawsdwqjsdlkw
    restart: always
    volumes:
      - kafka-data0:/bitnami/kafka
  
  kafka1:
    image: 'bitnami/kafka:latest'
    container_name: kafka1
    ports:
      - '19092:9092'
      - '19094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka0:9093,1@kafka1:9093,2@kafka2:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092,EXTERNAL://localhost:19094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_CFG_LOG_RETENTION_MS=60000 # Only retain messages for one minute
      - KAFKA_CFG_LOG_SEGMENT_BYTES=1073741824 # 1 GB
      - KAFKA_CFG_SEGMENT_MS=60000 # only retain segments for 1 hour
      - KAFKA_CFG_LOG_CLEANUP_POLICY=delete # delete log messages
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_KRAFT_CLUSTER_ID=asdsataoitawsdwqjsdlkw
    restart: always
    volumes:
      - kafka-data1:/bitnami/kafka
  
  kafka2:
    image: 'bitnami/kafka:latest'
    container_name: kafka2
    ports:
      - '29092:9092'
      - '29094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka0:9093,1@kafka1:9093,2@kafka2:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092,EXTERNAL://localhost:29094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_CFG_LOG_RETENTION_MS=60000 # Only retain messages for one minute
      - KAFKA_CFG_LOG_SEGMENT_BYTES=1073741824 # 1 GB
      - KAFKA_CFG_SEGMENT_MS=60000 # only retain segments for 1 hour
      - KAFKA_CFG_LOG_CLEANUP_POLICY=delete # delete log messages
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_KRAFT_CLUSTER_ID=asdsataoitawsdwqjsdlkw
    restart: always
    volumes:
      - kafka-data2:/bitnami/kafka

```

How to reproduce
================
Create a consumer and a three setup broker setup using Confluent.Kafka 2.3.0 and start by letting the consumer consume some messages. Then shut down broker1, then start it up again, then shut down broker2, then start it up again, then shut down broker3 and then start it up again, and then you will see it never receives messages again until you remake the consumer entirely.

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.
 - [x] Apache Kafka version - The newest available
 - [x] Client configuration.
 - [x] Operating system. - MacOs
 - [x] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [x] Critical issue.
