### ISSUE TITLE
Consumer.OnMessage cannot get any message

### ISSUE THREAD

**Issue by zicjin** [confluentinc/confluent-kafka-dotnet#616]
Description
===========
My consumer.OnPartitionsAssigned got the partition information, and with the help of kafka-manager I confirmed that there is a lot of data in the topic, but no matter how I try, OnMessage will not be called.

How to reproduce
================
this is my test code:
```
[HttpPut, Route("kafka_test_producer")]
public IActionResult KafkaTestProducer(string topic, string key, string content)
{
    // _kafkaOptions.Value.BootstrapServers: 10.135.123.27:9092
    try
    {
        _logger.LogWarning($"BootstrapServers {_kafkaOptions.Value.BootstrapServers} topic {topic} content {content}");

        var pconfig = new Dictionary<string, object> { { "bootstrap.servers", _kafkaOptions.Value.BootstrapServers } };
        using (var producer = new Producer<string, string>(pconfig, new StringSerializer(Encoding.UTF8), new StringSerializer(Encoding.UTF8)))
        {
            var dr = producer.ProduceAsync(topic, key, content).Result;
            _logger.LogWarning($"producer {dr.Key} {dr.Value}");
        }
    }
    catch (KafkaException ex)
    {
        _logger.LogError(ex, $"Delivery failed: {ex.Error.Reason}");
        throw;
    }

    return Ok();
}


[HttpPut, Route("kafka_test_consumer")]
public IActionResult KafkaTestConsumer(string topic, string groupid)
{
    var cconfig = new Dictionary<string, object>
    {
        { "group.id", groupid },
        { "bootstrap.servers", _kafkaOptions.Value.BootstrapServers },
        { "auto.commit.interval.ms", 5000 },
        { "auto.offset.reset", "earliest" }
    };

    using (var consumer = new Consumer<string, string>(cconfig, new StringDeserializer(Encoding.UTF8), new StringDeserializer(Encoding.UTF8)))
    {
        try
        {
            consumer.OnMessage += (_, msg) =>
            {
                _logger.LogWarning($"Read {msg.Topic} {msg.Key} from: {msg.TopicPartitionOffset}");
            };

            consumer.OnError += (_, error) =>
                _logger.LogError($"test consumer error: {error}");
            consumer.OnConsumeError += (_, msg) =>
                _logger.LogError($"test consumer consume error ({msg.TopicPartitionOffset}): {msg.Error}");

            consumer.OnPartitionsAssigned += (_, ps) =>
                _logger.LogWarning($"test partitions assigned: {string.Join(',', ps.Select(p => p.Topic + p.Partition))}");
            consumer.OnPartitionsRevoked += (_, ps) =>
                _logger.LogWarning($"test partitions revoked: {string.Join(',', ps.Select(p => p.Topic + p.Partition))}");

            consumer.Subscribe(topic);

            _logger.LogWarning($"consumer.Subscribe {string.Join(',', consumer.Subscription)}");
            while (true)
            {
                consumer.Poll(TimeSpan.FromMilliseconds(100));
            }
        }
        catch (Exception ex)
        {
            consumer.Unsubscribe();
            _logger.LogError(ex, $"test consumer Exception");
        }
    }

    return Ok();
}
```
I got every log from:
_logger.LogWarning($"producer {dr.Key} {dr.Value}");
_logger.LogWarning($"consumer.Subscribe {string.Join(',', consumer.Subscription)}");
_logger.LogWarning($"test partitions assigned: {string.Join(',', ps.Select(p => p.Topic + p.Partition))}");

![image](https://user-images.githubusercontent.com/199482/44918907-b5a07600-ad6e-11e8-87e2-3ae00b626fcd.png)

but this log inside onMessage does not appear always:
_logger.LogWarning($"Read {msg.Topic} {msg.Key} from: {msg.TopicPartitionOffset}");

this is my kafka docker-compose.yml:
```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: on-failure
    ports:
      - "2181:2181"
    volumes:
      - /data/edisk1/zk:/opt/zookeeper-3.4.9/data
  kafka_one:
    image: wurstmeister/kafka
    restart: on-failure
    depends_on:
      - "zookeeper"
    ports:
      - "9092:9092"
      - "9997:9997"
    environment:
      KAFKA_BROKER_ID: 201
      KAFKA_ADVERTISED_HOST_NAME: 10.135.162.228 #inside networkip
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      JMX_PORT: 9997
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=10.135.162.228 -Dcom.sun.management.jmxremote.rmi.port=9997
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/edisk1/kf:/var/lib/kafka
  kafka_manager:
    image: deric/kafka-manager:1.3.3.18
    restart: on-failure
    depends_on:
      - "zookeeper"
      - "kafka_one"
    ports:
      - "9192:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
```
I checked the docker logs of kafka and zookeeper and found no exception information.
Any information that can help me?

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 0.11.5
 - [x] Apache Kafka version: docker image wurstmeister/kafka:lastest
 - [ ] Client configuration:
 - [x] Operating system: ubuntu 16.04
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue
